---

- name: "Build Jenkins Pipeline with gradle"
  become: yes
  shell: |
      BUILD_STATUS=$(curl --user snapcheck:snapcheck --silent 34.216.71.67:8080/job/gradlepipe/build?token=palki123/api/json )