---
- name: "Build Jenkins Pipeline with gradle"
  become: yes
  shell: |
      ssh -l snapcheck -p 53801 34.223.248.132 build gradlepipe
      
- name: "Print Console output of Jenkins Pipeline"
  become: yes
  shell: |
      ssh -l snapcheck -p 53801 34.223.248.132 console gradlepipe
       
