---

- name: Pause for 1 min till container is up and running
  pause:
    minutes: 1
    
- name: "Build Jenkins Pipeline with gradle"
  become: yes
  become_user: ubuntu
  command: ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l snapcheck -p 53801 localhost build gradlepipe
  ignore_errors: yes
      
  
- name: Pause for 15 seconds for build to be over
  pause:
    seconds: 15
    

- name: "Get the console output"
  become: yes
  become_user: ubuntu
  shell: |
         ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l snapcheck -p 53801 localhost console gradlepipe 
  ignore_errors: yes
