---
- name: "Build Jenkins Pipeline with gradle"
  shell: |
      curl --user snapcheck:snapcheck --silent localhost:8080/job/gradlepipe/build

- name: "Get the conmsle output"
  shell: |
         curl --user snapcheck:snapcheck -s  localhost:8080/job/gradlepipe/lastBuild/consoleText
