---
- name: "Build Jenkins Pipeline with gradle"
  shell: |
      ssh -l palki -p 53801 localhost build gradlepipe
      
 - name: "Build Jenkins Pipeline with gradle"
  shell: |
      ssh -l palki -p 53801 localhost console gradlepipe
       
