---
- name: "Build Jenkins Pipeline with gradle"
  shell: |
      ssh -l snapcheck -p 53801 localhost build gradlepipe   
      
  
- name: Pause for 5 seconds for build to be over
  pause:
    seconds: 5
    

- name: "Get the console output"
  shell: |
         ssh -l snapcheck -p 53801 localhost console gradlepipe   
