jenkins: 
  agentProtocols:
  ## How jenkins controller and agent (master-slave) communicate
    - "JNLP4-connect"
  ## no. of executers in nothing but no. of jobs that this controller/slave can run parallely 
  numExecutors: 2
  securityRealm: 
    local: 
      allowsSignup: false 
      users: 
        - id: "admin"
          password: "admin"
        - id: "snapcheck"
          password: "snapcheck"
          properties:
            - sshPublicKey: 
                authorizedKeys: |
                  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRj2ivJFqK4QHcoVYxIPFNVJf9k7Zw8vcu0uNt8M+Bj4DeW2QEDEVxqsJZYMOS3/XqR73cMGB80rCEQRMvZrCF2uPLN3bl0EU18HvZlREZQHUFHYb9u8sWNQpEk7R593XwKO7/8JoZpUONfAIHt2IiNHJFCHj6ISDhA9/mHuXAN8QTyTS+YE2At4pi/rM8KOBy35V7GHEKQzeWx4Jb+FoDs0ljR/ha4sQdBUlaUvtz5bYzee2SVsyDkmWflUUmXUt0IFePXaQ0mysNjngwu28l2IX0JuKjpNhlVNidJ/F5Yvxo+K5Ywg/sVAMVG9Mtz4ulrDhVf+v2+DJUi9mVyisT ubuntu@ip-172-31-2-120
  authorizationStrategy: loggedInUsersCanDoAnything
tool:
 gradle:
  installations:
   - name: gradle
     home: /usr/bin/gradle
unclassified:
  location:
    url: http://52.11.82.37:8080
security:
  sSHD:
    port: 53801
jobs: 
  - file: /usr/local/seedjob.groovy
